### PR TITLE
Adds an Eq instance for SQLError

### PR DESCRIPTION
**Pull request by nkpart**
Just a derived one. This came up for me when doing some testing, an equality on the errors would've been handy.

### CODE REVIEW

**Comment by nurpax** [comment]
Thanks!

**Comment by nkpart** [comment]
@nurpax @IreneKnapp Could we get a release out with this patch in it?

**Comment by nurpax** [comment]
Sorry about the delay!  It should be on hackage in a minute.

**Comment by nkpart** [comment]
Thanks :)

**Pull request merged**
