### PR TITLE
Update sqlite to 3.20.1

### PR DESCRIPTION
**Pull request by mvoidex**
With json1 extension

### CODE REVIEW

**Comment by nurpax** [comment]
Hi @mvoidex, can update the PR with another commit that re-applies to Mac OS build fix, as in https://github.com/IreneKnapp/direct-sqlite/wiki/Hacking#upgrading-sqlite3?  Or if it's fixed in sqlite upstream, confirm that it's ok now.

The Travis failures seem to be related to a broken Travis misconfig.  I should try to fix that at some point.

**Comment by dunnl** [comment]
Can we update this to add -DSQLITE_ENABLE_FTS5? I've been playing around with this in issue #67 before I noticed this PR. I just confirmed that FTS5 works with 3.20.1

**Comment by mvoidex** [comment]
@nurpax, ok, I'll check when i have some time

**Comment by mvoidex** [comment]
@nurpax, can't test it on MacOS, but it seems, that nothing changed in upstream, so i've applied patch.
@dunnl, I'm fine with that; @nurpax, if you don't mind, I'll add `-DSQLITE_ENABLE_FTS5` under `fulltextsearch` flag condition

**Comment by nurpax** [comment]
@mvoidex Thanks!  please enable FTS5 too.  It seems like it's enabled at even in some distros (@dunnl said in another thread that he had FTS5 with -lsystemlib) so it does look like something we just wanna turn on.  It's not like direct-sqlite is going to be used in space-limited embedded systems.

**Comment by mvoidex** [comment]
@nurpax, what i've found at sqlite3.org:

> The json1 source code is included with the SQLite amalgamation, though it is disabled by default. Add the -DSQLITE_ENABLE_JSON1 compile-time option to enable the json1 extension that is built into the amalgamation. 

(http://www.sqlite.org/json1.html#compiling_the_json1_extension)

**Comment by nurpax** [comment]
Released to hackage as 2.3.21.  Thanks for the PR!

**Comment by mvoidex** [comment]
Cool, thanks!

**Pull request merged**
