### PR TITLE
add withDatabase, withStatement

### PR DESCRIPTION
**Pull request by ocramz**
a couple handy brackets

### CODE REVIEW

**Review by jchia — CHANGES_REQUESTED** [review]
Please rephrase the commit messages:

Added withDatabase
Added withStatement

**Comment by ocramz** [comment]
Hi, do I understand correctly my contribution was rejected because you
didn't like the commit message?
You do realize it's possible to rewrite those with a squash merge?

**Comment by jchia** [comment]
I didn't really reject the PR. I have pushed the commits myself with
updated commit messages as you can see, to quickly close loose ends.

**Comment by jchia** [comment]
A merge resulting in no additional commits and no difference to the commit history.

**Pull request merged**
